### ISSUE TITLE
SQL syntax error causing update_statement to upload sql messages incorrectly [MUST PROVIDE FIX ON CLOSE]

### ISSUE THREAD

**Issue by brandonhallKHA** [KimleyHorn/SigOpsTools#12]
Problem:
[2024-08-05T14:45:25.445Z] Traceback (most recent call last):
  File "C:\Development\Azure Deployments\CrashDataService\0.1 (Beta)\CrashDataTrigger\__init__.py", line 248, in insert_records_to_db
    cursor.executemany(update_statement, update_records)
  File "C:\Development\Azure Deployments\CrashDataService\0.1 (Beta)\CrashDataTrigger\.venv\Lib\site-packages\mysql\connector\cursor.py", line 659, in executemany
    self.execute(operation, params)
  File "C:\Development\Azure Deployments\CrashDataService\0.1 (Beta)\CrashDataTrigger\.venv\Lib\site-packages\mysql\connector\cursor.py", line 551, in execute
    self._handle_result(self._connection.cmd_query(stmt))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Development\Azure Deployments\CrashDataService\0.1 (Beta)\CrashDataTrigger\.venv\Lib\site-packages\mysql\connector\connection.py", line 490, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Development\Azure Deployments\CrashDataService\0.1 (Beta)\CrashDataTrigger\.venv\Lib\site-packages\mysql\connector\connection.py", line 395, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '%s, Description = %s, LanesAffected = %s, Detours = %s, PlannedEndDate = %s
    ' at line 2

**Comment by brandonhallKHA** [comment]
FIX: cursor must have sql elements in order and parsed out to correctly execute. DO NOT use cursor.executemany. My statement went from cursor.executemany(update_statement, update_records) to    cursor.execute(update_statement, (record.roadway_name, record.region, record.reported, record.last_updated, record.planned_end, record.description, record.latitude, record.longitude, record.travel_dir, record.event_type, record.subtype, record.lanesAffected, record.detours, record.ID))
